# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "e045e04dcef07b6af555d3f57a66fcc952f925d0bd8b090a6286dedb93d24b2b"  # generated for Coolify deployment 2026-06-12
  limiter: false
  image_proxy: true
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0
search:
    formats:
        - html
        - json